mode: MPIIFaceGaze
device: cuda
dataset:
  dataset_dir: datasets/MPIIFaceGaze.h5
transform:
  mpiifacegaze_face_size: 224
  mpiifacegaze_gray: False
model:
  name: resnet_simple
test:
  test_id: 0
  checkpoint: experiments/mpiifacegaze/resnet_50/exp00/00/checkpoint_0015.pth
  output_dir: experiments/mpiifacegaze/resnet_50/exp00/00/eval
  batch_size: 256
  dataloader:
    num_workers: 4
    pin_memory: False
cudnn:
  benchmark: True
  deterministic: False
